PS-5205 | duplicate entrypoint validation
3CLogicInc/nervecenter pull request #16
Opened 2023-07-26 12:06 UTC by darksun850

2023-07-28 07:55 UTC, ssrivastava9 approved these changes

2023-07-31 06:02 UTC, sumitchopra16 commented on src/main/resources/application.properties
> +server.port = 8888
This line need to be removed ?

2023-07-31 07:19 UTC, sumitchopra16 approved these changes

2023-07-31 07:20 UTC, sumitchopra16 requested changes

2023-07-31 07:20 UTC, sumitchopra16 commented on src/main/java/com/ccclogic/nerve/services/webastra/EntrypointServiceImpl.java
> +import feign.FeignException;
remove this line..

2023-07-31 08:27 UTC, sumitchopra16 approved these changes

2023-07-31 08:27 UTC, merged